with  BOM as (

    select * from SYNERGYSUITE.PUBLIC.TBL_BOM

),

CATEGORY as (

    select * from SYNERGYSUITE.PUBLIC.TBL_CATEGORY

),

COMPANY as (

    select * from SYNERGYSUITE.PUBLIC.TBL_COMPANY

),

COMPANYPRODUCT as (

    select * from SYNERGYSUITE.PUBLIC.TBL_COMPANYPRODUCT

),

DUTIES as (

    select * from SYNERGYSUITE.PUBLIC.TBL_DUTIES

),

PAYRATE as (

    select * from SYNERGYSUITE.PUBLIC.TBL_PAYRATE

),

PERSON as (

    select * from SYNERGYSUITE.PUBLIC.TBL_PERSON

),

POSTINGGROUP as (

    select * from SYNERGYSUITE.PUBLIC.TBL_POSTINGGROUP

),

PRODUCT as (

    select * from SYNERGYSUITE.PUBLIC.TBL_PRODUCT

),

ROSTERSECTION as (

    select * from SYNERGYSUITE.PUBLIC.TBL_ROSTERSECTION

),

UNITOFMEASURE as (

    select * from SYNERGYSUITE.PUBLIC.TBL_UNITOFMEASURE

),

VAT as (

    select * from SYNERGYSUITE.PUBLIC.TBL_VAT

),

SHIFTS as (

    select * from SYNERGYSUITE.PUBLIC.TBL_SHIFTS

),

STOCKTAKE as (

    select * from SYNERGYSUITE.PUBLIC.TBL_STOCKTAKE

),

STOCKTAKELINES as (

    select * from SYNERGYSUITE.PUBLIC.TBL_STOCKTAKELINES

),

TRANSACTIONDETAIL as (

    select * from SYNERGYSUITE.PUBLIC.TBL_TRANSACTIONDETAIL

),

TRANSACTIONHEADER as (

    select * from SYNERGYSUITE.PUBLIC.TBL_TRANSACTIONHEADER

),

PUNCTUALITYREPORT as (

    select * from SYNERGYSUITE.PUBLIC.TBL_PUNCTUALITYREPORT

),
appraisal as (

    select * from synergysuite.public.tbl_appraisal

),


final as (
 select 
	BOM.* 
	,CATEGORY.* 
	,COMPANY.*
	,COMPANYPRODUCT.*
	,DUTIES.*
	,PAYRATE.*
	,PERSON.*
	,POSTINGGROUP.*
	,PRODUCT.*
	,ROSTERSECTION.*
	,UNITOFMEASURE.*
	,VAT.*
	,SHIFTS.*
	,STOCKTAKE.*
	,STOCKTAKELINES.*
	,TRANSACTIONDETAIL.*
	,TRANSACTIONHEADER.*
	,PUNCTUALITYREPORT.*
	,appraisal.*

FROM PRODUCT 
LEFT JOIN CATEGORY USING(ID)
LEFT JOIN COMPANY USING(ID)
LEFT JOIN COMPANYPRODUCT USING(ID)
LEFT JOIN DUTIES USING(ID)
LEFT JOIN PAYRATE USING(ID)
LEFT JOIN PERSON USING(ID)
LEFT JOIN POSTINGGROUP USING(ID)
LEFT JOIN BOM USING(ID)
LEFT JOIN ROSTERSECTION USING(ID)
LEFT JOIN UNITOFMEASURE USING(ID)
LEFT JOIN VAT USING(ID)
LEFT JOIN SHIFTS USING(ID)
LEFT JOIN STOCKTAKE USING(ID)
LEFT JOIN STOCKTAKELINES USING(ID)
LEFT JOIN TRANSACTIONDETAIL USING(ID)
LEFT JOIN TRANSACTIONHEADER USING(ID)
LEFT JOIN PUNCTUALITYREPORT USING(ID)
LEFT JOIN appraisal USING(ID)

)

select * from final
 
  
